const LEADERBOARD_KEY = 'gradion_leaderboard';
const BADGES_KEY = 'gradion_badges';

const QUIZ_DATA = [
  {
    id: 'ai-fundamentals',
    name: 'AI Fundamentals',
    icon: '🧠',
    description: 'Core concepts of machine learning, neural networks, and AI systems.',
    questions: [
      { q: 'What does LLM stand for in AI?', opts: ['Large Language Model','Linear Learning Machine','Long Logic Module','Language Learning Matrix'], correct: 0, diff: 'easy', pts: 10, exp: 'LLM = Large Language Model. These are AI systems trained on vast text data to understand and generate human language.' },
      { q: 'Which learning paradigm trains a model using labeled input-output pairs?', opts: ['Unsupervised Learning','Reinforcement Learning','Supervised Learning','Transfer Learning'], correct: 2, diff: 'easy', pts: 10, exp: 'Supervised learning uses labeled training data — each input has a known correct output.' },
      { q: 'What is "overfitting" in machine learning?', opts: ['The model trains too slowly','The model memorises training data and generalises poorly','The model has too many layers','The model uses too little training data'], correct: 1, diff: 'medium', pts: 20, exp: 'Overfitting means the model learns training data noise rather than the underlying pattern, causing poor performance on new data.' },
      { q: 'What is the main innovation of the Transformer architecture?', opts: ['It uses convolutional layers','It introduces the self-attention mechanism','It eliminates the need for training data','It uses recurrent neural networks'], correct: 1, diff: 'hard', pts: 30, exp: 'Transformers introduced the self-attention mechanism, allowing models to weigh the importance of different parts of the input regardless of position.' },
      { q: 'What is a "token" in the context of language models?', opts: ['A security credential','A unit of text (word, sub-word, or character)','A training sample','A model parameter'], correct: 1, diff: 'medium', pts: 20, exp: 'Tokens are the basic units LLMs process — they can be words, parts of words, or characters depending on the tokeniser.' },
      { q: 'What is the purpose of an activation function in a neural network?', opts: ['To initialise weights','To introduce non-linearity into the model','To reduce overfitting','To increase training speed'], correct: 1, diff: 'hard', pts: 30, exp: 'Activation functions add non-linearity, enabling neural networks to learn complex patterns beyond simple linear relationships.' },
      { q: 'What is "inference" in AI?', opts: ['Training a model on new data','Using a trained model to make predictions','Evaluating model accuracy','Updating model weights'], correct: 1, diff: 'medium', pts: 20, exp: 'Inference is the process of using an already-trained model to generate predictions or outputs from new input data.' },
      { q: 'What does "training data" refer to?', opts: ['Data used to test the model','Data used to evaluate final model performance','Data used to teach the model patterns','Random data generated by the AI'], correct: 2, diff: 'easy', pts: 10, exp: 'Training data is the dataset the model learns from — it sees these examples during the training process.' },
      { q: 'What is "transfer learning"?', opts: ['Moving a model to a new server','Using knowledge from one task to improve performance on another','Transferring data between databases','Copying model weights to a new architecture'], correct: 1, diff: 'medium', pts: 20, exp: 'Transfer learning reuses a model trained on one task as the starting point for a new, related task — saving time and data.' },
      { q: 'In a neural network, what is a "layer"?', opts: ['A security boundary','A group of neurons that process information in parallel','A dataset partition','A training iteration'], correct: 1, diff: 'easy', pts: 10, exp: 'Layers are the building blocks of neural networks — each layer transforms its input into a new representation passed to the next layer.' }
    ]
  },
  {
    id: 'generative-ai',
    name: 'Generative AI',
    icon: '✨',
    description: 'LLMs, ChatGPT, Claude, prompting techniques, and generative models.',
    questions: [
      { q: 'Which company created ChatGPT?', opts: ['Google','Microsoft','OpenAI','Anthropic'], correct: 2, diff: 'easy', pts: 10, exp: 'ChatGPT was created by OpenAI, first released in November 2022.' },
      { q: 'What does RAG stand for?', opts: ['Rapid AI Generation','Retrieval-Augmented Generation','Recursive Algorithm Generator','Real-time AI Gateway'], correct: 1, diff: 'hard', pts: 30, exp: 'RAG = Retrieval-Augmented Generation. It combines a retrieval system (finding relevant documents) with a generative model to produce grounded, accurate answers.' },
      { q: 'What is "hallucination" in the context of AI?', opts: ['When AI generates images','When AI produces confident but false information','When the model is overloaded','When AI misidentifies images'], correct: 1, diff: 'medium', pts: 20, exp: 'AI hallucination refers to the model generating factually incorrect or fabricated information presented with apparent confidence.' },
      { q: 'What is Claude?', opts: ['An AI image generator','A text editor with AI features','An AI assistant created by Anthropic','A Google language model'], correct: 2, diff: 'easy', pts: 10, exp: 'Claude is Anthropic\'s AI assistant — a family of LLMs focused on being helpful, harmless, and honest.' },
      { q: 'What does GPT stand for?', opts: ['General Purpose Technology','Generative Pre-trained Transformer','Guided Prediction Tool','Graph Processing Technology'], correct: 1, diff: 'easy', pts: 10, exp: 'GPT = Generative Pre-trained Transformer — the architecture behind OpenAI\'s language models.' },
      { q: 'What is "zero-shot prompting"?', opts: ['Giving no prompt at all','Asking the model to perform a task with no examples provided','A prompt that requires no training','Using very short prompts'], correct: 1, diff: 'hard', pts: 30, exp: 'Zero-shot prompting means asking the model to perform a task without giving it any examples — relying entirely on its pre-trained knowledge.' },
      { q: 'What is "fine-tuning" an LLM?', opts: ['Adjusting the model\'s font display','Training a pre-trained model on a specific dataset to specialise it','Reducing the model size','Improving model speed'], correct: 1, diff: 'medium', pts: 20, exp: 'Fine-tuning adapts a pre-trained model to a specific domain or task by continuing training on a curated dataset.' },
      { q: 'What is a "context window" in an LLM?', opts: ['The UI window of a chat interface','The maximum amount of text the model can process at once','The model\'s visual input','The training dataset size'], correct: 1, diff: 'medium', pts: 20, exp: 'The context window is the maximum number of tokens (text) an LLM can consider in a single request — both input and output.' },
      { q: 'What is Stable Diffusion primarily used for?', opts: ['Writing code','Generating images from text prompts','Translating languages','Analysing data'], correct: 1, diff: 'easy', pts: 10, exp: 'Stable Diffusion is an open-source text-to-image generative AI model that creates images from text prompts.' },
      { q: 'What is "chain-of-thought" prompting?', opts: ['Linking multiple API calls','Instructing the model to reason step-by-step before answering','Using a chain of models','Storing conversation history'], correct: 1, diff: 'hard', pts: 30, exp: 'Chain-of-thought prompting encourages the model to show its reasoning process step by step, significantly improving accuracy on complex tasks.' }
    ]
  },
  {
    id: 'ai-tools',
    name: 'AI Tools & Productivity',
    icon: '🛠️',
    description: 'Developer tools, productivity apps, and practical AI integrations.',
    questions: [
      { q: 'What is GitHub Copilot primarily used for?', opts: ['Managing GitHub repositories','AI-powered code completion and generation','Running automated tests','Reviewing pull requests'], correct: 1, diff: 'easy', pts: 10, exp: 'GitHub Copilot is an AI coding assistant that suggests code completions, generates functions, and helps write documentation in real time.' },
      { q: 'What is Perplexity AI specialised in?', opts: ['Image generation','AI-powered search with cited sources','Code generation','Video editing'], correct: 1, diff: 'easy', pts: 10, exp: 'Perplexity AI is an AI search engine that provides answers with cited sources, combining web search with LLM reasoning.' },
      { q: 'What is LangChain used for?', opts: ['Translating programming languages','Building applications powered by LLMs','Securing AI models','Compressing ML models'], correct: 1, diff: 'medium', pts: 20, exp: 'LangChain is a framework for building applications using LLMs — it simplifies connecting models with data sources, APIs, and multi-step reasoning.' },
      { q: 'What is a vector database primarily used for in AI?', opts: ['Storing user login data','Storing and querying high-dimensional embeddings for semantic search','Managing relational data','Caching API responses'], correct: 1, diff: 'hard', pts: 30, exp: 'Vector databases store embeddings (numerical representations of text/images) and enable fast similarity searches — essential for RAG systems.' },
      { q: 'What is Hugging Face known for?', opts: ['Social media for developers','An open-source AI model hub and ML platform','A code editor','A cloud computing service'], correct: 1, diff: 'easy', pts: 10, exp: 'Hugging Face is the leading platform for open-source AI models, datasets, and machine learning tools — often called "the GitHub of AI".' },
      { q: 'What is an "AI agent"?', opts: ['A human AI trainer','An AI that autonomously takes actions to achieve goals','A chatbot plugin','A model evaluation metric'], correct: 1, diff: 'medium', pts: 20, exp: 'An AI agent autonomously perceives its environment, makes decisions, and takes actions (like browsing the web or writing code) to achieve a given goal.' },
      { q: 'What is Cursor?', opts: ['A mouse pointer AI','An AI-powered code editor built on VS Code','A database management tool','An AI image editor'], correct: 1, diff: 'easy', pts: 10, exp: 'Cursor is an AI-first code editor forked from VS Code that integrates LLM capabilities for editing, generating, and debugging code.' },
      { q: 'What is "model distillation"?', opts: ['Purifying training data','Compressing a large model\'s knowledge into a smaller model','Removing biased data','Speeding up model inference with hardware'], correct: 1, diff: 'hard', pts: 30, exp: 'Model distillation trains a smaller "student" model to replicate the behaviour of a larger "teacher" model, enabling faster and cheaper deployment.' },
      { q: 'What does an "embedding" represent in AI?', opts: ['An image file attachment','A numerical vector representation of text or data','A model\'s training checkpoint','A software dependency'], correct: 1, diff: 'medium', pts: 20, exp: 'Embeddings are dense numerical vectors that represent text, images, or other data — similar items have similar vector positions, enabling semantic operations.' },
      { q: 'What is AutoGPT?', opts: ['An automatic GPT account','An experimental AI agent that autonomously completes complex tasks','A faster version of GPT-4','A GPT fine-tuning tool'], correct: 1, diff: 'medium', pts: 20, exp: 'AutoGPT is an open-source AI agent that autonomously breaks down and executes multi-step tasks using tools like web browsing and code execution.' }
    ]
  }
];

function getLeaderboard() {
  try { return JSON.parse(localStorage.getItem(LEADERBOARD_KEY) || '[]'); } catch { return []; }
}

function saveLeaderboard(lb) {
  localStorage.setItem(LEADERBOARD_KEY, JSON.stringify(lb));
}

function addLeaderboardEntry(name, categoryId, score, maxScore, time) {
  const lb = getLeaderboard();
  lb.push({ name, categoryId, score, maxScore, time, date: new Date().toLocaleDateString() });
  lb.sort((a, b) => b.score - a.score);
  saveLeaderboard(lb.slice(0, 50));
}

function getUserBadges() {
  try { return JSON.parse(localStorage.getItem(BADGES_KEY) || '[]'); } catch { return []; }
}

function saveUserBadges(badges) {
  localStorage.setItem(BADGES_KEY, JSON.stringify(badges));
}

function awardBadge(id, name, icon) {
  const badges = getUserBadges();
  if (!badges.find(b => b.id === id)) {
    badges.push({ id, name, icon, earnedAt: new Date().toISOString() });
    saveUserBadges(badges);
    return true;
  }
  return false;
}

function checkAndAwardBadges(categoryId, score, maxScore, timeTaken, correctCount, totalQuestions, fastAnswers) {
  const earned = [];
  const pct = score / maxScore;

  if (awardBadge('first_quiz', 'First Quiz!', '🎯')) earned.push({ name: 'First Quiz!', icon: '🎯' });
  if (pct >= 0.8 && awardBadge(`hot_${categoryId}`, 'On Fire', '🔥')) earned.push({ name: 'On Fire', icon: '🔥' });
  if (pct === 1.0 && awardBadge(`perfect_${categoryId}`, 'Perfect Score', '🏆')) earned.push({ name: 'Perfect Score', icon: '🏆' });
  if (fastAnswers >= 5 && awardBadge('speed_demon', 'Speed Demon', '⚡')) earned.push({ name: 'Speed Demon', icon: '⚡' });
  if (getUserBadges().some(b => b.id === 'first_quiz') &&
      QUIZ_DATA.every(cat => getLeaderboard().some(e => e.categoryId === cat.id))) {
    if (awardBadge('all_categories', 'All-Rounder', '🌟')) earned.push({ name: 'All-Rounder', icon: '🌟' });
  }
  return earned;
}
